version:  '3.8'

services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_feed_bot
      PGDATA: /var/lib/postgresql/data/
    ports:
      - 5434:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: